#!/usr/bin/expect
#
# © Copyright 2016 Boku, Inc. All rights reserved.
#
set timeout 3

set username "rdelaney"
set password "s8aspAjA"
set serverno [lindex $argv 0]
set pckgname [lindex $argv 1]

log_user 0
spawn ssh qa01app-70$serverno

while {1} {
  expect {
    eof                             {break}
    "The authenticity of host"      {send_user "\[INFO\] Confirming authenticity of host." ; send "yes\r"}
    "*\]"                           {send_user "\[INFO\] Authenticity pre-verified. Continuing..." ; break}
  }
}

send "sudo su - paymo\r"
expect {
  "*password for $username:" {send_user "\n\[INFO\] Sending password for sudo..." ; send "$password\r"}
}

expect {
  "\[paymo@"  {
                send_user "\n\[INFO\] Changing to project directory...\n"
                send "cd /opt/javaapps/applications/\r"
                send "cd $pckgname\r"
                while {1} {
                  expect {
                    "*No such file or directory"    { send_user "\[ERROR\] Project directory not found.\n" ; send "\r" ; break }
                    }
                  expect {
                    "*\]"                           { send "ll\r"; send "ln -snf " ; break }
                    }
                  }
  }
}

interact

# vim: filetype=expect foldmethod=marker shiftwidth=2 expandtab softtabstop=4:
