#!/usr/bin/env bash
#

# Functions {{{1
verbose() {
  if [[ "$verbose" = "1" ]]; then
    echo "$1" >&2
  fi
}

error() {
  echo "$1" >&2
}
# }}}
# Parameters {{{1
#
while :
do
  case $1 in
    --help | -\?)
      usage
      exit 0
      ;;
    -v | --verbose)
      # Each instance of -v adds 1 to verbosity
      local verbose=$((verbose+1))
      shift
      ;;
    -r | --recipient)
      recipient="$2"
      shift
      ;;
    --) # End of all options
      shift
      break
      ;;
    -*)
      echo "FATAL: Unknown option : $1" >&2
      exit 1
      shift
      ;;
    *)  # no more options. Stop while loop
      break
      ;;
  esac
done
# }}}

if ! type query2file &> /dev/null; then echo "ERROR: Missing dependency: query2file" 1>&2; exit 1; fi
if ! type file2email &> /dev/null; then echo "ERROR: Missing dependency: file2email" 1>&2; exit 1; fi

file2email $( query2file "$1" )

# vim: ft=sh foldmethod=marker:
