#!/usr/bin/env bash
# GNU bash, version 4.2.25(1)-release (x86_64-pc-linux-gnu)
#
# © Copyright 2014 Ryan Delaney. All rights reserved.
# This work is distributed WITHOUT ANY WARRANTY whatsoever; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the README file for additional terms and conditions on your use of this
# software.
#

queryemail "mara@sierrautility.net ryan@sierrautility.net" "-f /home/ryan/jobs/unpaidInvoices.pgsql"
