---
version: 2.1

jobs:
  lint:
    docker:
      - image: python:3.7.6-buster
    steps:
      - checkout
      - run:
          name: Install build & test dependencies
          command: |
            pip install --disable-pip-version-check --progress-bar off --no-clean --isolated --no-cache-dir pre-commit
            apt-get update -qq && apt-get install -q shellcheck
      - run:
          name: Run pre-commit hooks on all files
          command: pre-commit run --all-files --show-diff-on-failure

workflows:
  pipeline:
    jobs:
      - lint
